#!/bin/bash
# commit_report.sh - 提交新报告到 git 并发送通知

FIELD="$1"
DATE="$2"
REPORT_PATH="$3"
REPO_DIR="/Users/alexyang/git_repo/follow_ad"

cd "$REPO_DIR"

# 检查文件是否存在
if [[ ! -f "$REPORT_PATH" ]]; then
    echo "[ERROR] Report not found: $REPORT_PATH"
    exit 1
fi

# 添加报告
git add "$REPORT_PATH"

# 同时添加已分析论文数据库（如果有更新）
if [[ -f ".analyzed_papers.json" ]]; then
    git add ".analyzed_papers.json"
fi

# 提交
COMMIT_MSG="Add weekly ${FIELD} research report for ${DATE}

Generated by paper-scholar automated system
- Field: ${FIELD}
- Date: ${DATE}
- Report: $(basename "$REPORT_PATH")

Co-Authored-By: Claude Sonnet 4 <noreply@anthropic.com>"

git commit -m "$COMMIT_MSG"

if [[ $? -eq 0 ]]; then
    echo "[$(date)] ✓ Report committed to git"

    # 发送 macOS 通知
    osascript -e "display notification \"Report saved: research_reports/$(basename "$REPORT_PATH")\" with title \"Paper Scholar: ${FIELD}\" subtitle \"Weekly report completed\" sound name \"Glass\""

    exit 0
else
    echo "[$(date)] ✗ Git commit failed"
    exit 1
fi
