#!/bin/bash
# commit_report.sh - 提交新报告到 git 并发送通知

FIELD="$1"
DATE="$2"
REPORT_PATH="$3"
REPO_DIR="/Users/alexyang/git_repo/follow_ad"

cd "$REPO_DIR"

# 检查文件是否存在
if [[ ! -f "$REPORT_PATH" ]]; then
    echo "[ERROR] Report not found: $REPORT_PATH"
    exit 1
fi

# 添加报告
git add "$REPORT_PATH"

# 同时添加已分析论文数据库（如果有更新）
if [[ -f ".analyzed_papers.json" ]]; then
    git add ".analyzed_papers.json"
fi

# 提交
COMMIT_MSG="Add weekly ${FIELD} research report for ${DATE}

Generated by paper-scholar automated system
- Field: ${FIELD}
- Date: ${DATE}
- Report: $(basename "$REPORT_PATH")

Co-Authored-By: Claude Sonnet 4 <noreply@anthropic.com>"

git commit -m "$COMMIT_MSG"

if [[ $? -eq 0 ]]; then
    echo "[$(date)] ✓ Report committed to git"

    # 发送 macOS 通知
    osascript -e "display notification \"Report saved: research_reports/$(basename "$REPORT_PATH")\" with title \"Paper Scholar: ${FIELD}\" subtitle \"Weekly report completed\" sound name \"Glass\""

    # 发送邮件通知（iOS 可收到）
    EMAIL_RECIPIENT="1922585801@qq.com"

    # 提取报告关键信息
    PAPER_COUNT=$(grep -c "^### [0-9]" "$REPORT_PATH" || echo "N/A")

    # 获取字段中文名
    case "$FIELD" in
        vla) FIELD_CN="VLA/端到端学习" ;;
        llm) FIELD_CN="大语言模型" ;;
        planning-control) FIELD_CN="规划与控制" ;;
        gpu-graphics) FIELD_CN="GPU加速/图形学" ;;
        mathematics) FIELD_CN="数学" ;;
        formal-logic) FIELD_CN="形式逻辑" ;;
        *) FIELD_CN="$FIELD" ;;
    esac

    # 生成 HTML 邮件正文并通过 SMTP 发送
    FIELD_PARAM="$FIELD" DATE_PARAM="$DATE" REPORT_PATH_PARAM="$REPORT_PATH" FIELD_CN_PARAM="$FIELD_CN" python3 << 'PYHTML'
import re
import os
import sys

def md_to_html(text):
    """将 Markdown 转换为 HTML"""
    import re
    import html

    # 1. 转换代码块（在其他转换之前，使用占位符）
    code_blocks = []
    def save_code_block(match):
        lang = match.group(1) if match.group(1) else ''
        code = match.group(2).strip()
        # HTML转义代码内容
        escaped_code = html.escape(code)
        code_html = f'<pre style="background: #f5f5f5; padding: 12px; border-radius: 6px; overflow-x: auto; margin: 16px 0; border-left: 3px solid #1a73e8;"><code style="font-family: monospace; font-size: 13px; color: #333;">{escaped_code}</code></pre>'
        placeholder = f'___CODE_BLOCK_{len(code_blocks)}___'
        code_blocks.append(code_html)
        return placeholder
    text = re.sub(r'```(\w+)?\n(.*?)```', save_code_block, text, flags=re.DOTALL)

    # 2. 保护数学公式（不转换，留给 MathJax 渲染）
    # 使用占位符保护公式，防止被后续的 markdown 转换影响
    math_formulas = []

    # 保护块级公式 $$...$$
    def save_block_math(match):
        formula = match.group(0)  # 保留完整的 $$...$$
        placeholder = f'___BLOCK_MATH_{len(math_formulas)}___'
        math_formulas.append(formula)
        return placeholder
    text = re.sub(r'\$\$.*?\$\$', save_block_math, text, flags=re.DOTALL)

    # 保护行内公式 $...$
    def save_inline_math(match):
        formula = match.group(0)  # 保留完整的 $...$
        placeholder = f'___INLINE_MATH_{len(math_formulas)}___'
        math_formulas.append(formula)
        return placeholder
    text = re.sub(r'\$[^\$]+\$', save_inline_math, text)

    # 3. 转换水平分隔线
    text = re.sub(r'^---+$', '<hr style="border: none; border-top: 2px solid #e0e0e0; margin: 24px 0;">', text, flags=re.MULTILINE)

    # 4. 转换表格
    table_pattern = r'\|(.+)\|\n\|[-:\s|]+\|\n((?:\|.+\|\n?)+)'
    def convert_table(match):
        header = match.group(1)
        rows = match.group(2)
        headers = [h.strip() for h in header.split('|') if h.strip()]
        html = '<table style="width:100%; border-collapse: collapse; margin: 16px 0;">'
        html += '<thead><tr>'
        for h in headers:
            html += f'<th style="border: 1px solid #ddd; padding: 10px; background: #f0f7ff; text-align: left; font-weight: 600;">{h}</th>'
        html += '</tr></thead><tbody>'
        for row in rows.strip().split('\n'):
            if row.strip():
                cells = [c.strip() for c in row.split('|') if c.strip()]
                html += '<tr>'
                for cell in cells:
                    html += f'<td style="border: 1px solid #ddd; padding: 10px;">{cell}</td>'
                html += '</tr>'
        html += '</tbody></table>'
        return html
    text = re.sub(table_pattern, convert_table, text, flags=re.MULTILINE)

    # 5. 转换标题（从h6到h1，避免冲突）
    text = re.sub(r'^######\s+(.+)$', r'<h6 style="font-size:14px;color:#666;margin:12px 0 6px 0;">\1</h6>', text, flags=re.MULTILINE)
    text = re.sub(r'^#####\s+(.+)$', r'<h5 style="font-size:15px;color:#757575;margin:14px 0 7px 0;">\1</h5>', text, flags=re.MULTILINE)
    text = re.sub(r'^####\s+(.+)$', r'<h4>\1</h4>', text, flags=re.MULTILINE)
    text = re.sub(r'^###\s+(.+)$', r'<h3>\1</h3>', text, flags=re.MULTILINE)
    text = re.sub(r'^##\s+(.+)$', r'<h2>\1</h2>', text, flags=re.MULTILINE)
    text = re.sub(r'^#\s+(.+)$', r'<h1>\1</h1>', text, flags=re.MULTILINE)

    # 6. 转换粗体
    text = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', text)

    # 7. 转换斜体
    text = re.sub(r'\*([^*]+)\*', r'<em>\1</em>', text)

    # 8. 转换链接 [text](url)
    text = re.sub(r'\[([^\]]+)\]\(([^\)]+)\)', r'<a href="\2" style="color: #1a73e8; text-decoration: none;">\1</a>', text)

    # 9. 处理列表和段落
    lines = text.split('\n')
    result = []
    in_list = False

    for line in lines:
        line_stripped = line.strip()

        # 跳过空行
        if not line_stripped:
            if in_list:
                result.append('</ul>')
                in_list = False
            result.append('<br>')
            continue

        # 已转换的HTML标签
        if line_stripped.startswith('<'):
            if in_list:
                result.append('</ul>')
                in_list = False
            result.append(line_stripped)
        # 列表项
        elif line_stripped.startswith('- '):
            if not in_list:
                result.append('<ul style="margin: 10px 0; padding-left: 28px;">')
                in_list = True
            item_content = line_stripped[2:]
            result.append(f'<li style="margin: 6px 0; line-height: 1.6;">{item_content}</li>')
        # 普通段落
        else:
            if in_list:
                result.append('</ul>')
                in_list = False
            result.append(f'<p style="margin: 10px 0; line-height: 1.8;">{line_stripped}</p>')

    if in_list:
        result.append('</ul>')

    html_output = '\n'.join(result)

    # 10. 恢复代码块
    for i, code_html in enumerate(code_blocks):
        html_output = html_output.replace(f'___CODE_BLOCK_{i}___', code_html)

    # 11. 恢复数学公式（让 MathJax 渲染）
    for i, formula in enumerate(math_formulas):
        # 分别处理块级和行内公式的占位符
        html_output = html_output.replace(f'___BLOCK_MATH_{i}___', formula)
        html_output = html_output.replace(f'___INLINE_MATH_{i}___', formula)

    return html_output

# 从环境变量读取参数
FIELD = os.environ.get('FIELD_PARAM', '')
DATE = os.environ.get('DATE_PARAM', '')
REPORT_PATH = os.environ.get('REPORT_PATH_PARAM', '')
FIELD_CN = os.environ.get('FIELD_CN_PARAM', '')

with open(REPORT_PATH, 'r') as f:
    content = f.read()

# 转换整个报告为 HTML（不仅仅是摘要）
# 移除第一行标题（因为邮件已有标题）
content_without_title = re.sub(r'^# .+\n', '', content)
# 移除元数据部分
content_without_meta = re.sub(r'\*\*生成时间\*\*:.*?\n---\n', '', content_without_title, flags=re.DOTALL)

# 转换完整报告
full_report_html = md_to_html(content_without_meta)

# 提取论文列表（统一正则，只匹配2或3个#）
papers = []

# 匹配: ## 或 ### 开头的论文标题
# ##\#? 表示: ## 后面可选第3个#，只匹配2或3个#
# 支持: ## 1. [2603.14523] Title 或 ### 1. Title
# 只在 Trend Analysis 之前搜索
trend_match = re.search(r'^## (Trend Analysis|趋势分析|Trend)', content, re.MULTILINE)
search_content = content[:trend_match.start()] if trend_match else content

for match in re.finditer(r'^##\#?\s+(\d+)\.\s+(?:\[([^\]]+)\]\s+)?(.+?)$', search_content, re.MULTILINE):
    num, arxiv_id, title = match.groups()
    # 过滤非论文标题
    title_clean = title.strip()
    if any(kw in title_clean for kw in ['趋势', '方向', '路径', '建议', '推荐', '分析', '概述', 'Summary']):
        continue

    papers.append({
        'num': num,
        'title': title_clean,
        'arxiv_id': arxiv_id.strip() if arxiv_id else 'N/A',
        'arxiv_url': f'https://arxiv.org/abs/{arxiv_id.strip()}' if arxiv_id else '#'
    })

# 生成 HTML
html = f'''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- MathJax for LaTeX rendering -->
    <script>
    MathJax = {{
        tex: {{
            inlineMath: [['$', '$']],
            displayMath: [['$$', '$$']],
            processEscapes: true
        }},
        options: {{
            skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
        }}
    }};
    </script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" async></script>

    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; line-height: 1.6; color: #333; max-width: 100%; margin: 0; padding: 20px; background: #f5f5f5; }}
        .container {{ background: white; border-radius: 12px; padding: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }}
        h1 {{ color: #1a73e8; margin-top: 0; font-size: 24px; }}
        .meta {{ background: #f0f7ff; padding: 16px; border-radius: 8px; margin: 16px 0; }}
        .meta-item {{ margin: 8px 0; font-size: 15px; }}
        .summary {{ background: white; padding: 0; margin: 20px 0; }}
        .summary h2 {{ font-size: 20px; color: #1a73e8; margin: 24px 0 12px 0; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }}
        .summary h3 {{ font-size: 18px; color: #d84315; margin: 20px 0 10px 0; }}
        .summary h4 {{ font-size: 16px; color: #f57c00; margin: 16px 0 8px 0; }}
        .summary p {{ margin: 10px 0; line-height: 1.8; font-size: 14px; }}
        .summary ul {{ margin: 10px 0; padding-left: 28px; }}
        .summary li {{ margin: 6px 0; line-height: 1.6; }}
        .summary strong {{ color: #d84315; }}
        .summary em {{ color: #666; }}
        .summary table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
        .summary th {{ border: 1px solid #ddd; padding: 10px; background: #f0f7ff; text-align: left; font-weight: 600; }}
        .summary td {{ border: 1px solid #ddd; padding: 10px; }}
        .summary a {{ color: #1a73e8; text-decoration: none; }}
        .summary a:hover {{ text-decoration: underline; }}
        .summary pre {{ background: #f5f5f5; padding: 12px; border-radius: 6px; overflow-x: auto; margin: 16px 0; border-left: 3px solid #1a73e8; }}
        .summary code {{ font-family: 'Monaco', 'Menlo', 'Courier New', monospace; font-size: 13px; color: #333; }}
        .summary hr {{ border: none; border-top: 2px solid #e0e0e0; margin: 24px 0; }}
        .papers {{ margin: 20px 0; }}
        .paper {{ background: #fafafa; padding: 12px; margin: 8px 0; border-radius: 6px; border-left: 3px solid #4caf50; }}
        .paper-title {{ font-weight: 600; color: #1a73e8; font-size: 15px; }}
        .paper-date {{ color: #666; font-size: 13px; margin-top: 4px; }}
        .paper-date a {{ color: #1a73e8; text-decoration: none; font-weight: 500; }}
        .paper-date a:hover {{ text-decoration: underline; }}
        .footer {{ margin-top: 24px; padding-top: 16px; border-top: 1px solid #eee; color: #666; font-size: 13px; }}
        @media (prefers-color-scheme: dark) {{
            body {{ background: #1a1a1a; color: #e0e0e0; }}
            .container {{ background: #2a2a2a; }}
            .meta {{ background: #1e3a5f; }}
            .summary {{ background: #2a2a2a; }}
            .summary h2 {{ color: #64b5f6; border-color: #444; }}
            .summary h3 {{ color: #ff9800; }}
            .summary h4 {{ color: #ffb74d; }}
            .summary p {{ color: #e0e0e0; }}
            .summary th {{ background: #1e3a5f; border-color: #444; }}
            .summary td {{ border-color: #444; }}
            .summary a {{ color: #64b5f6; }}
            .summary pre {{ background: #1e1e1e; border-color: #64b5f6; }}
            .summary code {{ color: #e0e0e0; }}
            .summary hr {{ border-color: #444; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📚 {FIELD_CN}领域研究周报</h1>

        <div class="meta">
            <div class="meta-item">📅 <strong>报告日期</strong>: {DATE}</div>
            <div class="meta-item">📊 <strong>分析论文</strong>: {len(papers)} 篇</div>
            <div class="meta-item">📁 <strong>完整报告</strong>: 见附件 .md 文件</div>
        </div>

        <div class="summary">
            {full_report_html}
        </div>

        <div class="footer">
            <div>📂 本地路径: {REPORT_PATH}</div>
            <div style="margin-top:12px; color:#999;">🤖 由 Paper Scholar 自动生成</div>
        </div>
    </div>
</body>
</html>'''

# ============ 使用 SMTP 直接发送邮件 (修复83GB内存泄漏) ============
import smtplib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

EMAIL_RECIPIENT = "1922585801@qq.com"
smtp_server = "smtp.qq.com"
smtp_port = 465  # SSL端口
sender_email = "1922585801@qq.com"
auth_code = os.environ.get('QQ_MAIL_AUTH_CODE', '')

if not auth_code:
    print("[ERROR] Missing QQ_MAIL_AUTH_CODE environment variable", file=sys.stderr)
    print("Please set: export QQ_MAIL_AUTH_CODE='your_auth_code'", file=sys.stderr)
    sys.exit(1)

# 构建邮件
msg = MIMEMultipart('mixed')
msg['From'] = f'Paper Scholar <{sender_email}>'
msg['To'] = EMAIL_RECIPIENT
msg['Subject'] = f'📚 {FIELD_CN}周报 - {DATE}'

# 添加HTML内容 (直接从内存发送,不写文件 - 避免AppleScript内存膨胀)
html_part = MIMEText(html, 'html', 'utf-8')
msg.attach(html_part)

# 添加markdown附件
try:
    with open(REPORT_PATH, 'rb') as f:
        attachment = MIMEBase('application', 'octet-stream')
        attachment.set_payload(f.read())
        encoders.encode_base64(attachment)
        filename = os.path.basename(REPORT_PATH)
        attachment.add_header('Content-Disposition', f'attachment; filename="{filename}"')
        msg.attach(attachment)
except Exception as e:
    print(f"[WARNING] Failed to attach report: {e}", file=sys.stderr)

# 发送邮件
try:
    import ssl
    # 创建SSL上下文 (禁用主机名检查以兼容macOS)
    context = ssl.create_default_context()
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    print(f"[INFO] Connecting to {smtp_server}:{smtp_port}...", file=sys.stderr)
    with smtplib.SMTP_SSL(smtp_server, smtp_port, context=context, timeout=30) as server:
        print("[INFO] Logging in...", file=sys.stderr)
        server.login(sender_email, auth_code)
        print("[INFO] Sending email...", file=sys.stderr)
        server.send_message(msg)
    print(f"[SUCCESS] Email sent to {EMAIL_RECIPIENT}", file=sys.stderr)
    sys.exit(0)
except smtplib.SMTPAuthenticationError:
    print("[ERROR] SMTP authentication failed - check QQ_MAIL_AUTH_CODE", file=sys.stderr)
    sys.exit(1)
except Exception as e:
    print(f"[ERROR] Email send failed: {e}", file=sys.stderr)
    sys.exit(1)
PYHTML

    if [[ $? -eq 0 ]]; then
        echo "[$(date)] ✓ Email sent to ${EMAIL_RECIPIENT}"
        exit 0
    else
        echo "[$(date)] ✗ Email send failed (check QQ_MAIL_AUTH_CODE)"
        exit 1
    fi
else
    echo "[$(date)] ✗ Git commit failed"
    exit 1
fi
